// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeuL8AHsMfDC7vf2D-Z9_V1R2rJmWqHQ',
    appId: '1:1095291124527:web:72dbbf107369edadf93fda',
    messagingSenderId: '1095291124527',
    projectId: 'queue-manager-bb479',
    authDomain: 'queue-manager-bb479.firebaseapp.com',
    storageBucket: 'queue-manager-bb479.appspot.com',
    measurementId: 'G-59SYCEB9BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXlxOLtccRUIPs0__aEycUU-QVm35cQfg',
    appId: '1:1095291124527:android:9fcc8c9f7cee5df7f93fda',
    messagingSenderId: '1095291124527',
    projectId: 'queue-manager-bb479',
    storageBucket: 'queue-manager-bb479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg196SjwYC5omphw7azt1IQRnQ0dcwoJE',
    appId: '1:1095291124527:ios:14de784522a72e92f93fda',
    messagingSenderId: '1095291124527',
    projectId: 'queue-manager-bb479',
    storageBucket: 'queue-manager-bb479.appspot.com',
    iosClientId: '1095291124527-l7ev9stpnjqrj7ft81hcs7tah4kb3ps8.apps.googleusercontent.com',
    iosBundleId: 'com.example.queueManager',
  );
}
